const supabaseUrl = "https://oviwrtpeswwyvzdycxyc.supabase.co";

const supabaseSecretKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92aXdydHBlc3d3eXZ6ZHljeHljIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTM0NzEwNTEsImV4cCI6MjAwOTA0NzA1MX0.AIBjYznK3MFh6Psx3oEqM9yn-GSGyyNHnK97-3n1QUU";
