// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKNH75hprun4Emw_djrEV9OhMEU9eWI88',
    appId: '1:523157331508:web:697641476bdbe686aa3461',
    messagingSenderId: '523157331508',
    projectId: 'savetime-4f221',
    authDomain: 'savetime-4f221.firebaseapp.com',
    storageBucket: 'savetime-4f221.appspot.com',
    measurementId: 'G-GEHELHCYMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_8U0rX_aT-LZZt62B9AlB__tFMtgU-dw',
    appId: '1:523157331508:android:0e6e3ecb59b65fc9aa3461',
    messagingSenderId: '523157331508',
    projectId: 'savetime-4f221',
    storageBucket: 'savetime-4f221.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx-sYDtkEnnsU8t3dGt5k_1fT5WdDSoiE',
    appId: '1:523157331508:ios:c89e97bf145953fcaa3461',
    messagingSenderId: '523157331508',
    projectId: 'savetime-4f221',
    storageBucket: 'savetime-4f221.appspot.com',
    iosClientId: '523157331508-0itnjb6pled94eh6l18gnl1jfn6bvjvo.apps.googleusercontent.com',
    iosBundleId: 'com.pro.savetime.savetime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx-sYDtkEnnsU8t3dGt5k_1fT5WdDSoiE',
    appId: '1:523157331508:ios:c89e97bf145953fcaa3461',
    messagingSenderId: '523157331508',
    projectId: 'savetime-4f221',
    storageBucket: 'savetime-4f221.appspot.com',
    iosClientId: '523157331508-0itnjb6pled94eh6l18gnl1jfn6bvjvo.apps.googleusercontent.com',
    iosBundleId: 'com.pro.savetime.savetime',
  );
}
